window.menuData=[
    {
        "id":"homePage",
        "text":"首页",
        "component":'./components/home.html',
    },
    {
        "id":"aboutD",
        "text":"关于达英和",
        "component":'./components/abouts.html'
    }
];